schedule:
  # dates: yyyy-mm-dd
  start_date: "2026-07-01"
  end_date: "2026-09-30"

  submission_deadline: "2026-06-15"

  allowed_weekdays:
    - 2   # Tuesday
    - 6   # Saturday

service_information:

  Tuesday:
    time: "18:00 - 19:00"

  Saturday:
    time: "10:00 - 12:00"

volunteers:
  - name: Renata
    email: renata.pocitarenco19@gmail.com

  - name: Drache
    email: drache@gmail.com

  - name: Leo
    email: rr@gmail.com

  - name: Zundino
    email: fierrrsta@gmail.com

  - name: Leorr
    email: rrrrrr@gmail.com

  - name: Zundineeeo
    email: fieeeeesta@gmail.com

  - name: Lesssso
    email: rsssr@gmail.com

  - name: Zundinsdfo
    email: fieshjjjta@gmail.com